// src/services/royaltyEarnings.service.ts
import { BaseApiService, type APIResponse } from './api.service';

/**
 * A single royalty event generated by a secondary-market key transfer.
 * Mirrors the shape returned by GET /creators/:creatorId/royalties so the
 * earnings breakdown can render each row without further mapping (issue #987).
 */
export interface RoyaltyEarningsEvent {
	/** Unique royalty event identifier used as the React list key. */
	id: string;
	/** Unix timestamp (milliseconds) of the secondary transfer. */
	timestamp: number;
	/** Transfer amount in XLM that generated the royalty. */
	transferAmount: number;
	/** Royalty earned by the creator from this transfer, in XLM. */
	royaltyEarned: number;
}

/** Claimed royalty payout, resolved on-chain. */
export interface RoyaltyClaim {
	/** Unique claim identifier used as the React list key. */
	id: string;
	/** Unix timestamp (milliseconds) of the claim transaction. */
	timestamp: number;
	/** Amount claimed, in XLM. */
	amount: number;
	/** On-chain transaction hash of the claim. */
	txHash: string;
}

/** Response envelope for GET /creators/:creatorId/royalties. */
export interface RoyaltyEarnings {
	/** Total royalties ever earned from secondary transfers, in XLM. */
	totalEarned: number;
	/** Royalties accrued but not yet claimed, in XLM. */
	pending: number;
	/** Royalties already claimed via withdraw transactions, in XLM. */
	claimed: number;
	/** Per-transfer royalty events, newest first. */
	events: RoyaltyEarningsEvent[];
	/** Successfully claimed payouts, newest first. */
	claims: RoyaltyClaim[];
}

class RoyaltyEarningsService extends BaseApiService {
	async getRoyaltyEarnings(creatorId: string): Promise<RoyaltyEarnings> {
		try {
			const response = await this.api.get<APIResponse<RoyaltyEarnings>>(
				`/creators/${creatorId}/royalties`
			);
			return response.data.data;
		} catch (error) {
			throw this.handleError(error);
		}
	}
}

export const royaltyEarningsService = new RoyaltyEarningsService();
