#!/usr/bin/env sh
export PATH="$PATH:/c/Program Files/Git/bin:/c/Program Files/Git/usr/bin:C:/Program Files/Git/bin:C:/Program Files/Git/usr/bin"

sh ./scripts/check-no-package-lock.sh
npx lint-staged

